### ISSUE TITLE
access denied in my first try

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/DevExpress.PackageContent#1]
```
Install-Module XpandPosh
Register-PackageSource –ProviderName Nuget –Name DX_private –Location https://nuget.devexpress.com/xxxxxxxxxxx/api
Install-DX -binPath c:\bin\ -dxSources $(Get-PackageSourceLocations -join ";") -sourcePath c:\tfs\ -dxVersion 18.2.5 
Update-HintPath –OutputPath c:\bin\ –SourcesPath c:\tfs\
`PS C:\temp> .\compile.ps1

```
Se necesita el proveedor de NuGet para continuar
PowerShellGet necesita la versión del proveedor de NuGet '2.8.5.201' o posterior para interactuar con repositorios
basados en NuGet. El proveedor de NuGet debe estar disponible en 'C:\Program
Files\PackageManagement\ProviderAssemblies' o
'C:\Users\administrador\AppData\Local\PackageManagement\ProviderAssemblies'. También puedes instalar el proveedor de
NuGet ejecutando 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. ¿Quieres que PowerShellGet se
instale e importe el proveedor de NuGet ahora?
[S] Sí  [N] No  [U] Suspender  [?] Ayuda (el valor predeterminado es "S"): S

Repositorio que no es de confianza
Estás instalando los módulos desde un repositorio que no es de confianza. Si confías en este repositorio, cambia su
valor InstallationPolicy ejecutando el cmdlet Set-PSRepository. ¿Estás seguro de que quieres instalar los módulos de
'PSGallery'?
[S] Sí  [O] Sí a todo  [N] No  [T] No a todo  [U] Suspender  [?] Ayuda (el valor predeterminado es "N"): O

Name                             ProviderName     IsTrusted  Location
----                             ------------     ---------  --------
DX_private                       NuGet            False      https://nuget.devexpress.com/xxxxxxxx...
Installing DX assemblies from https://www.powershellgallery.com/api/v2;https://nuget.devexpress.com/xxxxxxxxxxx/api
Get-ChildItem : Acceso denegado a la ruta de acceso 'C:\Windows\System32\LogFiles\WMI\RtBackup'.
En C:\Program Files\WindowsPowerShell\Modules\XpandPosh\1.0.12\public\Install-DX.ps1: 33 Carácter: 13
+     $nugets=Get-ChildItem $sourcePath *.csproj -Recurse|ForEach-Objec ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\Syst...es\WMI\RtBackup:String) [Get-ChildItem], Unauthoriz
   edAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
`

**Comment by apobekiaris** [comment]
I cannot read Spanish but almost understand that it prompts you to do something like?

```ps1
Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201
```

**Comment by apobekiaris** [comment]
also to avoid confirmations you can use the `-Force` switch

**Comment by vimarx** [comment]
the last error was about permisssions
Get-ChildItem :  Access denied 'C:\Windows\System32\LogFiles\WMI\RtBackup'.
En C:\Program Files\WindowsPowerShell\Modules\XpandPosh\1.0.12\public\Install-DX.ps1: 33 Carácter: 13

$nugets=Get-ChildItem $sourcePath *.csproj -Recurse|ForEach-Objec ...
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : PermissionDenied: (C:\Windows\Syst...es\WMI\RtBackup:String) [Get-ChildItem], Unauthoriz
edAccessException
FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
`

**Comment by vimarx** [comment]
> I cannot read Spanish but almost understand that it prompts you to do something like?
> 
> ```powershell
> Install-PackageProvider -Name Nuget -MinimumVersion 2.8.5.201
> ```

I accepted
